"""
This is a setup.py script generated by py2applet

Usage:
    python2.7 setup.py py2app
"""

from setuptools import setup

APP = ['Cecilia4Csound.py']
APP_NAME = 'Cecilia4Csound'
DATA_FILES = ['Resources/']
OPTIONS = {'argv_emulation': False,
           #'strip': False, # only for debugging purposes.
           'iconfile': 'Resources/Cecilia.icns',
           'includes': 'pyo,pyo.lib',
           'packages': 'pyo.lib.snds,pyo.examples,pyo.examples,pyo.examples.01-intro,pyo.examples.02-controls,pyo.examples.03-generators,pyo.examples.04-soundfiles,pyo.examples.05-envelopes,pyo.examples.06-filters,pyo.examples.07-effects,pyo.examples.08-dynamics,pyo.examples.09-callbacks,pyo.examples.10-tables,pyo.examples.16-midi,pyo.examples.18-multicore,pyo.examples.19-multirate,pyo.examples.algorithmic,pyo.examples.control,pyo.examples.effects,pyo.examples.fft,pyo.examples.matrix,pyo.examples.sampling,pyo.examples.sequencing,pyo.examples.snds,pyo.examples.synthesis,pyo.examples.tables,pyo.examples.utilities,pyo.examples.wxgui'
          }

setup(
    name=APP_NAME,
    app=APP,
    data_files=DATA_FILES,
    options={'py2app': OPTIONS},
    setup_requires=['py2app'],
)
