{'Array Opcodes': ['copya2ftab',
                   'copyf2array',
                   'maxarray',
                   'minarray',
                   'scalearray',
                   'sumarray'],
 'FLTK': {'Appearance': ['FLcolor',
                         'FLcolor2',
                         'FLhide',
                         'FLlabel',
                         'FLsetAlign',
                         'FLsetBox',
                         'FLsetColor',
                         'FLsetColor2',
                         'FLsetFont',
                         'FLsetPosition',
                         'FLsetSize',
                         'FLsetText',
                         'FLsetTextColor',
                         'FLsetTextSize',
                         'FLsetTextType',
                         'FLshow'],
          'Containers': ['FLgroup',
                         'FLgroupEnd',
                         'FLpack',
                         'FLpackEnd',
                         'FLpanel',
                         'FLpanelEnd',
                         'FLscroll',
                         'FLscrollEnd',
                         'FLtabs',
                         'FLtabsEnd'],
          'Other': ['FLbox',
                    'FLbutBank',
                    'FLbutton',
                    'FLcloseButton',
                    'FLexecButton',
                    'FLgetsnap',
                    'FLhvsBox',
                    'FLkeyIn',
                    'FLloadsnap',
                    'FLmouse',
                    'FLprintk',
                    'FLprintk2',
                    'FLrun',
                    'FLsavesnap',
                    'FLsetsnap',
                    'FLsetSnapGroup',
                    'FLsetVal',
                    'FLsetVal_i',
                    'FLslidBnk',
                    'FLslidBnk2',
                    'FLslidBnk2Set',
                    'FLslidBnk2Setk',
                    'FLslidBnkGetHandle',
                    'FLslidBnkSet',
                    'FLslidBnkSetk',
                    'FLupdate',
                    'FLvalue',
                    'FLvkeybd',
                    'FLvslidBnk',
                    'FLvslidBnk2',
                    'FLxyin',
                    'vphaseseg'],
          'Valuators': ['FLcount',
                        'FLjoy',
                        'FLknob',
                        'FLroller',
                        'FLslider',
                        'FLtext']},
 'Faust Opcodes': ['ihandle,a1[,a2,...] faustaudio',
                   'ihandle faustcompile',
                   'faustctl',
                   'ihandle,a1[,a2,...] faustgen'],
 'Image Processing Opcodes': ['imagecreate',
                              'imagefree',
                              'imagegetpixel',
                              'imageload',
                              'imagesave',
                              'imagesetpixel',
                              'imagesize'],
 'Instrument Control': {'Clock Control': ['clockoff', 'clockon'],
                        'Compilation': ['compileorc',
                                        'compilestr',
                                        'evalstr',
                                        'return'],
                        'Conditional Values': ['o',
                                               'p',
                                               'c',
                                               'd',
                                               'e',
                                               'n',
                                               'a',
                                               'm'],
                        'Duration Control': ['ihold',
                                             'turnoff',
                                             'turnoff2',
                                             'turnon'],
                        'Initialization and Reinitialization': ['=',
                                                                'init',
                                                                'nstrnum',
                                                                'p',
                                                                'passign',
                                                                'pset',
                                                                'reinit',
                                                                'rigoto',
                                                                'rireturn',
                                                                'tival'],
                        'Invocation': ['event',
                                       'event_i',
                                       'mute',
                                       'readscore',
                                       'remove',
                                       'schedkwhen',
                                       'schedkwhennamed',
                                       'schedule',
                                       'schedwhen',
                                       'scoreline',
                                       'scoreline_i'],
                        'Program Flow Control': ['cggoto',
                                                 'cigoto',
                                                 'ckgoto',
                                                 'cngoto',
                                                 'else',
                                                 'o',
                                                 'p',
                                                 'c',
                                                 'd',
                                                 'e',
                                                 'n',
                                                 'a',
                                                 'm',
                                                 'endif',
                                                 'goto',
                                                 'if',
                                                 'igoto',
                                                 'kgoto',
                                                 'then',
                                                 'loop_ge',
                                                 'loop_gt',
                                                 'loop_le',
                                                 'loop_lt',
                                                 'tigoto',
                                                 'timout'],
                        'Realtime Performance Control': ['active',
                                                         'cpumeter',
                                                         'cpuprc',
                                                         'exitnow',
                                                         'jacktransport',
                                                         'maxalloc',
                                                         'prealloc'],
                        'Sensing and Control': ['button',
                                                'changed',
                                                'checkbox',
                                                'control',
                                                'follow',
                                                'follow2',
                                                'getcfg',
                                                'joystick',
                                                'metro',
                                                'miditempo',
                                                'p5gconnect',
                                                'p5gdata',
                                                'pcount',
                                                'peak',
                                                'pindex',
                                                'pitch',
                                                'pitchamdf',
                                                'plltrack',
                                                'ptrack',
                                                'readscratch',
                                                'rewindscore',
                                                'rms',
                                                'sensekey',
                                                'seqtime',
                                                'seqtime2',
                                                'setctrl',
                                                'setscorepos ipos',
                                                'splitrig',
                                                'tempest',
                                                'tempo',
                                                'tempoval',
                                                'timedseq',
                                                'trigger',
                                                'trigseq',
                                                'wiiconnect',
                                                'wiidata',
                                                'wiirange',
                                                'wiisend',
                                                'writescratch',
                                                'xyin'],
                        'Stacks': ['pop', 'pop_f', 'push', 'push_f', 'stack'],
                        'Subinstrument Control': ['subinstr', 'subinstrinit'],
                        'Time Reading': ['date',
                                         'dates',
                                         'readclock',
                                         'rtclock',
                                         'timeinstk',
                                         'timeinsts',
                                         'timek',
                                         'times']},
 'Jacko Opcodes': ['JackoAudioIn ',
                   'JackoAudioInConnect ',
                   'JackoAudioOut ',
                   'JackoAudioOutConnect ',
                   'JackoFreewheel ',
                   'JackoInfo ',
                   'JackoInit ',
                   'JackoMidiInConnect ',
                   'JackoMidiOut ',
                   'JackoMidiOutConnect ',
                   'JackoNoteOut ',
                   'JackoOn ',
                   'JackoTransport '],
 'Lua Opcodes': ['lua_exec',
                 'lua_iopcall',
                 'lua_ikopcall',
                 'lua_iaopcall',
                 'lua_iopcall_off',
                 'lua_ikopcall_off',
                 'lua_iaopcall_off',
                 'lua_opdef'],
 'Mathematical Operations': {'Amplitude Functions': ['ampdb',
                                                     'ampdbfs',
                                                     'db',
                                                     'dbamp',
                                                     'dbfsamp'],
                             'Arithmetic and Logic Operations': ['+',
                                                                 '/',
                                                                 '%',
                                                                 '*',
                                                                 '&&',
                                                                 '&',
                                                                 '~',
                                                                 '|',
                                                                 '<<',
                                                                 '>>',
                                                                 '#',
                                                                 '||',
                                                                 '^',
                                                                 '-'],
                             'Comparators and Accumulators': ['clear',
                                                              'vincr'],
                             'Mathematical Functions': ['abs',
                                                        'ceil',
                                                        'exp',
                                                        'floor',
                                                        'frac',
                                                        'int',
                                                        'log',
                                                        'log10',
                                                        'log2',
                                                        'logbtwo',
                                                        'powoftwo',
                                                        'qinf',
                                                        'qnan',
                                                        'round',
                                                        'sqrt'],
                             'Opcode Equivalents of Functions': ['divz',
                                                                 'mac',
                                                                 'maca',
                                                                 'polynomial',
                                                                 'pow',
                                                                 'product',
                                                                 'sum',
                                                                 'taninv2'],
                             'Random Functions': ['birnd', 'rnd'],
                             'Trigonometric Functions': ['cos',
                                                         'cosh',
                                                         'cosinv',
                                                         'signum',
                                                         'sin',
                                                         'sinh',
                                                         'sininv',
                                                         'tan',
                                                         'tanh',
                                                         'taninv']},
 'Miscellaneous': ['fareylen',
                   'fareyleni',
                   'modmatrix',
                   'pwd',
                   'system_i',
                   'system',
                   'tableshuffle',
                   'tableshufflei'],
 'Mixer Opcodes': ['MixerClear',
                   'MixerGetLevel',
                   'MixerReceive',
                   'MixerSend',
                   'MixerSetLevel',
                   'MixerSetLevel_i'],
 'Network': ['remoteport',
             'sockrecv',
             'sockrecvs',
             'strecv',
             'socksend',
             'socksends',
             'stsend'],
 'OSC': ['OSCinit', 'OSClisten', 'OSCsend'],
 'Orchestra Syntax': {'Block Statements': ['endin',
                                           'endop',
                                           'instr',
                                           'opcode'],
                      'Header': ['0dbfs',
                                 'kr',
                                 'ksmps',
                                 'nchnls',
                                 'nchnls_i',
                                 'sr'],
                      'Macros': ['#define',
                                 '$NAME',
                                 '#end',
                                 '#include',
                                 '#undef']},
 'Pitch Converters': {'Functions': ['cent',
                                    'cpsmidinn',
                                    'cpsoct',
                                    'cpspch',
                                    'octave',
                                    'octcps',
                                    'octmidinn',
                                    'octpch',
                                    'pchmidinn',
                                    'pchoct',
                                    'semitone'],
                      'Tuning Opcodes': ['cps2pch',
                                         'cpstun',
                                         'cpstuni',
                                         'cpsxpch']},
 'Plugin Hosting': {'DSSI and LADSPA': ['dssiactivate',
                                        'dssiaudio',
                                        'dssictls',
                                        'dssiinit',
                                        'dssilist'],
                    'VST': ['vstaudio',
                            'vstaudiog',
                            'vstbankload',
                            'vstedit',
                            'vstinfo',
                            'vstinit',
                            'vstmidiout',
                            'vstnote',
                            'vstparamset ',
                            'vstparamget ',
                            'vstprogset']},
 'Python Opcodes': ['pyassign',
                    'pyassigni',
                    'pylassign',
                    'pylassigni',
                    'pyassignt',
                    'pylassignt',
                    'pycall',
                    'pycall1',
                    'pycall2',
                    'pycall3',
                    'pycall4',
                    'pycall5',
                    'pycall6',
                    'pycall7',
                    'pycall8',
                    'pycallt',
                    'pycall1t',
                    'pycall2t',
                    'pycall3t',
                    'pycall4t',
                    'pycall5t',
                    'pycall6t',
                    'pycall7t',
                    'pycall8t',
                    'pycalli',
                    'pycall1i',
                    'pycall2i',
                    'pycall3i',
                    'pycall4i',
                    'pycall5i',
                    'pycall6i',
                    'pycall7i',
                    'pycall8i',
                    'pycalln',
                    'pycallni',
                    'pylcall',
                    'pylcall1',
                    'pylcall2',
                    'pylcall3',
                    'pylcall4',
                    'pylcall5',
                    'pylcall6',
                    'pylcall7',
                    'pylcall8',
                    'pylcallt',
                    'pylcall1t',
                    'pylcall2t',
                    'pylcall3t',
                    'pylcall4t',
                    'pylcall5t',
                    'pylcall6t',
                    'pylcall7t',
                    'pylcall8t',
                    'pylcalli',
                    'pylcall1i',
                    'pylcall2i',
                    'pylcall3i',
                    'pylcall4i',
                    'pylcall5i',
                    'pylcall6i',
                    'pylcall7i',
                    'pylcall8i',
                    'pylcalln',
                    'pylcallni',
                    'pyeval',
                    'pyevali',
                    'pyleval',
                    'pylevali',
                    'pyevalt',
                    'pylevalt',
                    'pyexec',
                    'pyexeci',
                    'pylexec',
                    'pylexeci',
                    'pyexect',
                    'plyexect',
                    'pyinit',
                    'pyrun',
                    'pyruni',
                    'pylrun',
                    'pylruni',
                    'pyrunt',
                    'pylrunt'],
 'Real-time MIDI': {'Converters': ['ampmidi',
                                   'ampmidid',
                                   'cpsmidi',
                                   'cpsmidib',
                                   'cpstmid',
                                   'octmidi',
                                   'octmidib',
                                   'pchmidi',
                                   'pchmidib'],
                    'Event Extenders': ['release', 'xtratim'],
                    'Generic I/O': ['midiin', 'midiout'],
                    'Input': ['aftouch',
                              'chanctrl',
                              'ctrl14',
                              'ctrl21',
                              'ctrl7',
                              'ctrlinit',
                              'initc14',
                              'initc21',
                              'initc7',
                              'massign',
                              'midic14',
                              'midic21',
                              'midic7',
                              'midictrl',
                              'notnum',
                              'pchbend',
                              'pgmassign',
                              'polyaft',
                              'veloc'],
                    'MIDI/Score Interoperability': ['midichannelaftertouch',
                                                    'midichn',
                                                    'midicontrolchange',
                                                    'mididefault',
                                                    'midinoteoff',
                                                    'midinoteoncps',
                                                    'midinoteonkey',
                                                    'midinoteonoct',
                                                    'midinoteonpch',
                                                    'midipitchbend',
                                                    'midipolyaftertouch',
                                                    'midiprogramchange'],
                    'Note Output': ['midion',
                                    'midion2',
                                    'moscil',
                                    'noteoff',
                                    'noteon',
                                    'noteondur',
                                    'noteondur2'],
                    'Output': ['nrpn',
                               'outiat',
                               'outic',
                               'outic14',
                               'outipat',
                               'outipb',
                               'outipc',
                               'outkat',
                               'outkc',
                               'outkc14',
                               'outkpat',
                               'outkpb',
                               'outkpc'],
                    'Slider Banks': ['s16b14',
                                     's32b14',
                                     'slider16',
                                     'slider16f',
                                     'slider16table',
                                     'slider16tablef',
                                     'slider32',
                                     'slider32f',
                                     'slider32table',
                                     'slider32tablef',
                                     'slider64',
                                     'slider64f',
                                     'slider64table',
                                     'slider64tablef',
                                     'slider8',
                                     'slider8f',
                                     'slider8table',
                                     'slider8tablef',
                                     'sliderKawai'],
                    'System Realtime': ['mclock', 'mrtmsg']},
 'Remote Opcodes': ['insglobal', 'insremot', 'midglobal', 'midremot'],
 'Serial I/O': ['serialBegin',
                'serialEnd',
                'serialFlush',
                'serialPrint',
                'serialRead',
                'serialWrite',
                'serialWrite_i'],
 'Signal Flow Graph Opcodes': ['alwayson',
                               'connect ',
                               'ftgenonce',
                               'inleta ',
                               'inletf ',
                               'inletk ',
                               'inletkid ',
                               'outleta ',
                               'outletf ',
                               'outletk ',
                               'outletkid '],
 'Signal Generators': {'Additive Synthesis/Resynthesis': ['adsyn',
                                                          'adsynt',
                                                          'adsynt2',
                                                          'hsboscil'],
                       'Basic Oscillators': ['lfo',
                                             'oscbnk',
                                             'oscil',
                                             'oscil3',
                                             'oscili',
                                             'oscilikt',
                                             'osciliktp',
                                             'oscilikts',
                                             'osciln',
                                             'oscils',
                                             'poscil',
                                             'poscil3',
                                             'vibr',
                                             'vibrato'],
                       'Dynamic Spectrum Oscillators': ['buzz',
                                                        'gbuzz',
                                                        'mpulse',
                                                        'vco',
                                                        'vco2',
                                                        'vco2ft',
                                                        'vco2ift',
                                                        'vco2init'],
                       'Envelope Generators': ['adsr',
                                               'envlpx',
                                               'envlpxr',
                                               'linen',
                                               'linenr',
                                               'madsr',
                                               'mxadsr',
                                               'xadsr'],
                       'FM Synthesis': ['crossfm',
                                        'crossfmi',
                                        'crosspm',
                                        'crosspmi',
                                        'crossfmpm',
                                        'crossfmpmi',
                                        'fmb3',
                                        'fmbell',
                                        'fmmetal',
                                        'fmpercfl',
                                        'fmrhode',
                                        'fmvoice',
                                        'fmwurlie',
                                        'foscil',
                                        'foscili'],
                       'Granular Synthesis': ['diskgrain',
                                              'fof',
                                              'fof2',
                                              'fog',
                                              'grain',
                                              'grain2',
                                              'grain3',
                                              'granule',
                                              'partikkel',
                                              'partikkelsync',
                                              'sndwarp',
                                              'sndwarpst',
                                              'syncgrain',
                                              'syncloop',
                                              'vosim'],
                       'Hyper Vectorial Synthesis': ['hvs1', 'hvs2', 'hvs3'],
                       'Linear and Exponential Generators': ['cosseg',
                                                             'cossegb',
                                                             'cossegr',
                                                             'expcurve',
                                                             'expon',
                                                             'expseg',
                                                             'expsega',
                                                             'expsegb',
                                                             'expsegba',
                                                             'expsegr',
                                                             'gainslider',
                                                             'jspline',
                                                             'line',
                                                             'linseg',
                                                             'linsegb',
                                                             'linsegr',
                                                             'logcurve',
                                                             'loopseg',
                                                             'loopsegp',
                                                             'looptseg',
                                                             'loopxseg',
                                                             'lpshold',
                                                             'lpsholdp',
                                                             'rspline',
                                                             'scale',
                                                             'transeg',
                                                             'transegb',
                                                             'transegr'],
                       'Models and Emulations': ['bamboo',
                                                 'barmodel',
                                                 'cabasa',
                                                 'chuap',
                                                 'crunch',
                                                 'dripwater',
                                                 'gendy',
                                                 'gendyc',
                                                 'gendyx',
                                                 'gogobel',
                                                 'guiro',
                                                 'lorenz',
                                                 'mandel',
                                                 'mandol',
                                                 'marimba',
                                                 'moog',
                                                 'planet',
                                                 'prepiano',
                                                 'sandpaper',
                                                 'sekere',
                                                 'shaker',
                                                 'sleighbells',
                                                 'stix',
                                                 'tambourine',
                                                 'vibes',
                                                 'voice'],
                       'Phasors': ['phasor', 'phasorbnk', 'syncphasor'],
                       'Random (Noise) Generators': ['betarand',
                                                     'bexprnd',
                                                     'cauchy',
                                                     'cauchyi',
                                                     'cuserrnd',
                                                     'duserrnd',
                                                     'dust',
                                                     'dust2',
                                                     'exprand',
                                                     'exprandi',
                                                     'fractalnoise',
                                                     'gauss',
                                                     'gaussi',
                                                     'gausstrig',
                                                     'jitter',
                                                     'jitter2',
                                                     'linrand',
                                                     'noise',
                                                     'pcauchy',
                                                     'pinkish',
                                                     'poisson',
                                                     'rand',
                                                     'randh',
                                                     'randi',
                                                     'random',
                                                     'randomh',
                                                     'randomi',
                                                     'rnd31',
                                                     'seed',
                                                     'trandom',
                                                     'trirand',
                                                     'unirand',
                                                     'urandom',
                                                     'urd',
                                                     'weibull'],
                       'STK Opcodes': ['STKBandedWG',
                                       'STKBeeThree',
                                       'STKBlowBotl',
                                       'STKBlowHole',
                                       'STKBowed',
                                       'STKBrass',
                                       'STKClarinet',
                                       'STKDrummer',
                                       'STKFMVoices',
                                       'STKFlute',
                                       'STKHevyMetl',
                                       'STKMandolin',
                                       'STKModalBar',
                                       'STKMoog',
                                       'STKPercFlut',
                                       'STKPlucked',
                                       'STKResonate',
                                       'STKRhodey',
                                       'STKSaxofony',
                                       'STKShakers',
                                       'STKSimple',
                                       'STKSitar',
                                       'STKStifKarp',
                                       'STKTubeBell',
                                       'STKVoicForm',
                                       'STKWhistle',
                                       'STKWurley'],
                       'Sample Playback': ['bbcutm',
                                           'bbcuts',
                                           'flooper',
                                           'flooper2',
                                           'fluidAllOut',
                                           'fluidCCi',
                                           'fluidCCk',
                                           'fluidControl',
                                           'fluidEngine',
                                           'fluidLoad',
                                           'fluidNote',
                                           'fluidOut',
                                           'fluidProgramSelect',
                                           'fluidSetInterpMethod',
                                           'loscil',
                                           'loscil3',
                                           'loscilx',
                                           'lphasor',
                                           'lposcil',
                                           'lposcil3',
                                           'lposcila',
                                           'lposcilsa',
                                           'lposcilsa2',
                                           'sfilist',
                                           'sfinstr',
                                           'sfinstr3',
                                           'sfinstr3m',
                                           'sfinstrm',
                                           'sfload',
                                           'sflooper',
                                           'sfpassign',
                                           'sfplay',
                                           'sfplay3',
                                           'sfplay3m',
                                           'sfplaym',
                                           'sfplist',
                                           'sfpreset',
                                           'sndloop',
                                           'waveset'],
                       'Scanned Synthesis': ['scanhammer',
                                             'scans',
                                             'scantable',
                                             'scanu',
                                             'xscanmap',
                                             'xscans',
                                             'xscansmap',
                                             'xscanu'],
                       'Table Access': ['oscil1',
                                        'oscil1i',
                                        'ptable',
                                        'ptable3',
                                        'ptablei',
                                        'tab_i',
                                        'tab',
                                        'tabw_i',
                                        'tabw',
                                        'table',
                                        'table3',
                                        'tablei'],
                       'Wave Terrain Synthesis': [],
                       'Waveguide Physical Modeling': ['pluck',
                                                       'repluck',
                                                       'streson',
                                                       'wgbow',
                                                       'wgbowedbar',
                                                       'wgbrass',
                                                       'wgclar',
                                                       'wgflute',
                                                       'wgpluck',
                                                       'wgpluck2']},
 'Signal I/O': {'File I/O': ['dumpk',
                             'dumpk2',
                             'dumpk3',
                             'dumpk4',
                             'ficlose',
                             'fin',
                             'fini',
                             'fink',
                             'fiopen',
                             'fout',
                             'fouti',
                             'foutir',
                             'foutk',
                             'fprintks',
                             'fprints',
                             'readf',
                             'readfi',
                             'readk',
                             'readk2',
                             'readk3',
                             'readk4'],
                'Printing and Display': ['dispfft',
                                         'display',
                                         'flashtxt',
                                         'print',
                                         'printf_i',
                                         'printf',
                                         'printk',
                                         'printk2',
                                         'printks',
                                         'prints'],
                'Signal Input': ['diskin',
                                 'diskin2',
                                 'in',
                                 'in32',
                                 'inch',
                                 'inh',
                                 'ino',
                                 'inq',
                                 'inrg',
                                 'ins',
                                 'invalue',
                                 'inx',
                                 'inz',
                                 'mp3in',
                                 'soundin'],
                'Signal Output': ['mdelay',
                                  'monitor',
                                  'out',
                                  'out32',
                                  'outc',
                                  'outch',
                                  'outh',
                                  'outo',
                                  'outq',
                                  'outq1',
                                  'outq2',
                                  'outq3',
                                  'outq4',
                                  'outrg',
                                  'outs',
                                  'outs1',
                                  'outs2',
                                  'outvalue',
                                  'outx',
                                  'outz',
                                  'soundout',
                                  'soundouts'],
                'Software Bus': ['chani',
                                 'chano',
                                 'chn_k',
                                 'chn_a',
                                 'chn_S',
                                 'chnclear',
                                 'chnexport',
                                 'chnget',
                                 'chnmix',
                                 'chnparams',
                                 'chnrecv',
                                 'chnsend',
                                 'chnset',
                                 'setksmps',
                                 'xin',
                                 'xout'],
                'Soundfile Queries': ['filebit',
                                      'filelen',
                                      'filenchnls',
                                      'filepeak',
                                      'filesr',
                                      'filevalid',
                                      'mp3len']},
 'Signal Modifiers': {'Amplitude Modifiers': ['balance',
                                              'clip',
                                              'compress',
                                              'dam',
                                              'gain'],
                      'Comparators and Accumulators': ['max',
                                                       'max_k',
                                                       'maxabs',
                                                       'maxabsaccum',
                                                       'maxaccum',
                                                       'min',
                                                       'minabs',
                                                       'minabsaccum',
                                                       'minaccum'],
                      'Convolution and Morphing': ['convolve',
                                                   'cross2',
                                                   'dconv',
                                                   'ftconv',
                                                   'ftmorf',
                                                   'pconvolve'],
                      'Delay': ['delay',
                                'delay1',
                                'delayk ',
                                'vdel_k ',
                                'delayr',
                                'delayw',
                                'deltap',
                                'deltap3',
                                'deltapi',
                                'deltapn',
                                'deltapx',
                                'deltapxw',
                                'multitap',
                                'newopcodename',
                                'vdelay',
                                'vdelay3',
                                'vdelayx',
                                'vdelayxq',
                                'vdelayxs',
                                'vdelayxw',
                                'vdelayxwq',
                                'vdelayxws'],
                      'Panning and Spatialization': ['bformdec',
                                                     'bformdec1',
                                                     'bformenc',
                                                     'bformenc1',
                                                     'hrtfearly',
                                                     'hrtfer',
                                                     'hrtfmove',
                                                     'hrtfmove2',
                                                     'hrtfreverb',
                                                     'hrtfstat',
                                                     'locsend',
                                                     'locsig',
                                                     'pan',
                                                     'pan2',
                                                     'space',
                                                     'spat3d',
                                                     'spat3di',
                                                     'spat3dt',
                                                     'spdist',
                                                     'spsend',
                                                     'vbap',
                                                     'vbap16',
                                                     'vbap16move',
                                                     'vbap4',
                                                     'vbap4move',
                                                     'vbap8',
                                                     'vbap8move',
                                                     'vbapg',
                                                     'vbaplsinit',
                                                     'vbapmove',
                                                     'vbapz',
                                                     'vbapzmove'],
                      'Reverberation': ['alpass',
                                        'babo',
                                        'comb',
                                        'combinv',
                                        'freeverb',
                                        'nestedap',
                                        'nreverb',
                                        'platerev',
                                        'reverb',
                                        'reverb2',
                                        'reverbsc',
                                        'valpass',
                                        'vcomb'],
                      'Sample Level Operators': ['denorm',
                                                 'diff',
                                                 'downsamp',
                                                 'fold',
                                                 'integ',
                                                 'interp',
                                                 'ntrpol',
                                                 'a',
                                                 'i',
                                                 'k',
                                                 'samphold',
                                                 'upsamp',
                                                 'vaget',
                                                 'vaset'],
                      'Signal Limiters': ['limit', 'mirror', 'wrap'],
                      'Special Effects': ['distort',
                                          'distort1',
                                          'flanger',
                                          'harmon',
                                          'harmon2',
                                          'harmon3',
                                          'harmon4',
                                          'phaser1',
                                          'phaser2'],
                      'Specialized Filters': ['dcblock',
                                              'dcblock2',
                                              'eqfil',
                                              'filter2',
                                              'fofilter',
                                              'hilbert',
                                              'nlfilt',
                                              'nlfilt2',
                                              'pareq',
                                              'rbjeq',
                                              'zfilter2'],
                      'Standard Filters': ['atone',
                                           'atonex',
                                           'biquad',
                                           'biquada',
                                           'butbp',
                                           'butbr',
                                           'buthp',
                                           'butlp',
                                           'butterbp',
                                           'butterbr',
                                           'butterhp',
                                           'butterlp',
                                           'clfilt',
                                           'doppler',
                                           'median',
                                           'mediank',
                                           'mode',
                                           'tone',
                                           'tonex',
                                           'areson',
                                           'bqrez',
                                           'lowpass2',
                                           'lowres',
                                           'lowresx',
                                           'lpf18',
                                           'moogladder',
                                           'moogvcf',
                                           'moogvcf2',
                                           'reson',
                                           'resonr',
                                           'resonx',
                                           'resony',
                                           'resonz',
                                           'rezzy',
                                           'statevar',
                                           'svfilter',
                                           'tbvcf',
                                           'vlowres',
                                           'aresonk',
                                           'atonek',
                                           'lineto',
                                           'port',
                                           'portk',
                                           'resonk',
                                           'resonxk',
                                           'tlineto',
                                           'tonek'],
                      'Waveguides': ['wguide1', 'wguide2'],
                      'Waveshaping': ['chebyshevpoly',
                                      'pdclip',
                                      'pdhalf',
                                      'pdhalfy',
                                      'powershape']},
 'Spectral Processing': {'ATS': ['ATSadd',
                                 'ATSaddnz',
                                 'ATSbufread',
                                 'ATScross',
                                 'ATSinfo',
                                 'ATSinterpread',
                                 'ATSpartialtap',
                                 'ATSread',
                                 'ATSreadnz',
                                 'ATSsinnoi'],
                         'LPC': ['lpfreson',
                                 'lpinterp',
                                 'lpread',
                                 'lpreson',
                                 'lpslot'],
                         'Loris': ['lorismorph', 'lorisplay', 'lorisread'],
                         'Non-Standard': ['specaddm',
                                          'specdiff',
                                          'specdisp',
                                          'specfilt',
                                          'spechist',
                                          'specptrk',
                                          'specscal',
                                          'specsum',
                                          'spectrum'],
                         'Other': ['centroid', 'mincer', 'temposcal'],
                         'STFT': ['ktableseg',
                                  'pvadd',
                                  'pvbufread',
                                  'pvcross',
                                  'pvinterp',
                                  'pvoc',
                                  'pvread',
                                  'tableseg',
                                  'tablexseg',
                                  'vpvoc'],
                         'Streaming': ['binit',
                                       'partials',
                                       'pvs2tab',
                                       'pvsadsyn',
                                       'pvsanal',
                                       'pvsarp',
                                       'pvsbandp',
                                       'pvsbandr',
                                       'pvsbin',
                                       'pvsblur',
                                       'pvsbuffer',
                                       'pvsbufread',
                                       'pvsbufread2',
                                       'pvscale',
                                       'pvscent',
                                       'pvscross',
                                       'pvsdemix',
                                       'pvsdiskin',
                                       'pvsdisp',
                                       'pvsfilter',
                                       'pvsfread',
                                       'pvsfreeze',
                                       'pvsftr',
                                       'pvsftw',
                                       'pvsfwrite',
                                       'pvsgain',
                                       'pvshift',
                                       'pvsifd',
                                       'pvsin',
                                       'pvsinfo',
                                       'pvsinit',
                                       'pvslock',
                                       'pvsmaska',
                                       'pvsmix',
                                       'pvsmooth',
                                       'pvsmorph',
                                       'pvsosc',
                                       'pvsout',
                                       'pvspitch',
                                       'pvstanal',
                                       'pvstencil',
                                       'pvsvoc',
                                       'pvswarp',
                                       'pvsynth',
                                       'resyn',
                                       'sinsyn',
                                       'tab2pvs',
                                       'tradsyn',
                                       'trcross',
                                       'trfilter',
                                       'trhighest',
                                       'trlowest',
                                       'trmix',
                                       'trscale',
                                       'trshift',
                                       'trsplit']},
 'Strings': {'Conversion': ['strchar',
                            'strchark',
                            'strlower',
                            'strlowerk',
                            'strtod',
                            'strtodk',
                            'strtol',
                            'strtolk',
                            'strupper',
                            'strupperk'],
             'Definition': ['strget', 'strset'],
             'Manipulation': ['puts',
                              'sprintf',
                              'sprintfk',
                              'strcat',
                              'strcatk',
                              'strcmp',
                              'strcmpk',
                              'strcpy',
                              '=',
                              'strcpyk',
                              'strindex',
                              'strindexk',
                              'strlen',
                              'strlenk',
                              'strrindex',
                              'strrindexk',
                              'strsub',
                              'strsubk']},
 'Table Control': {'': ['ftfree', 'ftgen', 'ftgentmp', 'sndload'],
                   'Dynamic Selection': ['tableikt', 'tablekt', 'tablexkt'],
                   'Read/Write Opreations': ['ftload',
                                             'ftloadk',
                                             'ftsave',
                                             'ftsavek',
                                             'ptablew',
                                             'tablecopy',
                                             'tablefilter',
                                             'tablefilteri',
                                             'tablegpw',
                                             'tableicopy',
                                             'tableigpw',
                                             'tableimix',
                                             'tableiw',
                                             'tablemix',
                                             'tablera',
                                             'tablew',
                                             'tablewa',
                                             'tablewkt',
                                             'tabmorph',
                                             'tabmorpha',
                                             'tabmorphak',
                                             'tabmorphi',
                                             'tabplay',
                                             'tabrec'],
                   'Table Queries': ['array',
                                     'fillarray',
                                     'ftchnls',
                                     'ftcps',
                                     'ftlen',
                                     'ftlptim',
                                     'ftsr',
                                     'genarray',
                                     'genarray_i',
                                     'lenarray',
                                     'maparray',
                                     'maparray_i',
                                     'nsamp',
                                     'slicearray',
                                     'tableng',
                                     'tabsum',
                                     'tb0_init',
                                     'tb1_init',
                                     'tb2_init',
                                     'tb3_init',
                                     'tb4_init',
                                     'tb5_init',
                                     'tb6_init',
                                     'tb7_init',
                                     'tb8_init',
                                     'tb9_init',
                                     'tb10_init',
                                     'tb11_init',
                                     'tb12_init',
                                     'tb13_init',
                                     'tb14_init',
                                     'tb15_init',
                                     'tb0',
                                     'tb1',
                                     'tb2',
                                     'tb3',
                                     'tb4',
                                     'tb5',
                                     'tb6',
                                     'tb7',
                                     'tb8',
                                     'tb9',
                                     'tb10',
                                     'tb11',
                                     'tb12',
                                     'tb13',
                                     'tb14',
                                     'tb15']},
 'Vectorial': {'Cellular Automata': ['cell', 'vcella'],
               'Delay Paths': ['vdelayk', 'vecdelay', 'vport'],
               'Envelopes': ['vexpseg', 'vlinseg'],
               'Limiting and Wrapping': ['vlimit', 'vmirror', 'vwrap'],
               'Random': ['vrandh', 'vrandi'],
               'Scalar operations': ['vadd',
                                     'vadd_i',
                                     'vexp',
                                     'vexp_i',
                                     'vmult',
                                     'vmult_i',
                                     'vpow',
                                     'vpow_i'],
               'Tables': ['vtaba',
                          'vtabi',
                          'vtabk',
                          'vtable1k',
                          'vtablea',
                          'vtablei',
                          'vtablek',
                          'vtablewa',
                          'vtablewi',
                          'vtablewk',
                          'vtabwa',
                          'vtabwi',
                          'vtabwk'],
               'Vectorial operations': ['vaddv',
                                        'vaddv_i',
                                        'vcopy',
                                        'vcopy_i',
                                        'vdivv',
                                        'vdivv_i',
                                        'vexpv',
                                        'vexpv_i',
                                        'vmap',
                                        'vmultv',
                                        'vmultv_i',
                                        'vpowv',
                                        'vpowv_i',
                                        'vsubv',
                                        'vsubv_i']},
 'Zak Patch System': ['zacl',
                      'zakinit',
                      'zamod',
                      'zar',
                      'zarg',
                      'zaw',
                      'zawm',
                      'zir',
                      'ziw',
                      'ziwm',
                      'zkcl',
                      'zkmod',
                      'zkr',
                      'zkw',
                      'zkwm']}